package com.phoenixredwolf.prodweb.utility

object Constants {
    const val LINKEDIN = "https://www.linkedin.com/company/phoenixredwolf"
    const val FACEBOOK = "https://www.facebook.com/PhoenixRedwolfDigitalServices"
    const val CONSULT = "Start with an initial consultation to determine what the needs of your business are."
    const val IMPLEMENT = "Next we'll build a roadmap, create, and implement the perfect solutions."
    const val SUPPORT = "Train all members of your business on the new systems. Provide additional support as needed."
    const val CONTACT = "https://calendly.com/admin-fjs/30min"
    const val PRIVACYMAIL = "mailto:contact@phoenixredwolf.com?subject=Privacy Policy"
    const val CALL_LINK = "tel:8563470392"
    const val TOAST_LINK = "http://localpartners.toasttab.com/register-advocate/referred-by/BarretVogtman/"
}

object Res {
    object Image {
        const val logo = "/images/PRDSLogo.svg"
        const val logo2 = "/images/PRDSLogo2.svg"
        const val icon = "/images/PRDSIcon.svg"
        const val collaboration = "/images/collaboration-600x340.jpg"
        const val corporate = "/images/corporate-600x434.jpg"
        const val empower = "/images/empower-600x394.jpg"
        const val solution = "/images/solutions-600x360.jpg"
        const val success = "/images/success-600x344.jpg"
        const val webdev = "/images/webdev.jpg"
        const val webdevlg = "/images/webdevlg.jpg"
        const val tag1 = "/images/tagline1.svg"
        const val tag2 = "/images/tagline2.svg"
        const val managedservices = "/images/it-man-serv.png"
        const val managedserviceslg = "/images/it-man-serv-lg.jpg"
        const val itsupport = "/images/it-support.png"
        const val itsupportlg = "/images/it-support-lg.jpg"
        const val cloudserv = "/images/cloud-services.png"
        const val cloudservlg = "/images/cloud-services-lg.jpg"
        const val network = "/images/networksupport.jpg"
        const val networklg = "/images/networksupportlg.jpg"
        const val webdevcard = "/images/webDevCard.jpg"
        const val softwaredev = "/images/softwareDev.jpg"
        const val softwaredevlg = "/images/softwaredevlg.jpg"
        const val possystem = "/images/posSystems.jpg"
        const val possystemlg = "/images/posSystemslg.jpg"
        const val itconsult = "/images/itconsult.jpg"
        const val itconsultlg = "/images/itconsultlg.jpg"
        const val socmed = "/images/socialmedia.jpg"
        const val socmedlg = "/images/socialmedialg.jpg"
        const val itoper = "/images/itoperations.jpg"
        const val itoperlg = "/images/itoperationslg.jpg"
        const val cyber = "/images/cyber.jpg"
        const val cyberlg = "/images/cyberlg.jpg"
        const val risk = "/images/risk.jpg"
        const val risklg = "/images/risklg.jpg"
        const val voip = "/images/telesystems.jpg"
        const val voiplg = "/images/telesystemslg.jpg"
        const val ucaas = "/images/ucaas.jpg"
        const val ucaaslg = "/images/ucaaslg.jpg"
        const val train = "/images/training.jpg"
        const val recruit = "/images/recruiting.jpg"
        const val recruitlg = "/images/recruitinglg.jpg"
        const val transform = "/images/transform.jpg"
        const val transformlg = "/images/transformlg.jpg"
        const val brand = "/images/branding.jpg"
        const val brandlg = "/images/brandinglg.jpg"
        const val phone = "/images/ringingphone.gif"
        const val cell = "/images/cellphone.gif"
    }
}